version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app/api
      - /app/api/node_modules
    environment:
      - NODE_ENV=development 